# Site settings
title: Industrial Fing Optimisation
email: sean.m.hayes@umail.ucc.ie
description: > # this means to ignore newlines until "baseurl:"
  This blog documents industrial energy efficiency optimisation research.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.indoptim.ie" # the base hostname & protocol for your site
twitter_username: shayes02
github_username:  seanmhayes

# Build settings
markdown: kramdown